using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _clientids
{
    class _allnpcs
    {
        public static string[] allNpcCharacters = {
                "Officer Jackson",
                "Officer Green",
                "Officer Murphy",
                "Officer Howard",
                "Officer Lopez",
                "Officer Davis",
                "Officer Bailey",
                "Officer Lee",
                "Officer Sanchez",
                "Officer Cooper",
                "Officer Leo",
                "Kyle",
                "Uncle Nelson",
                "Kathy",
                "Anna",
                "Frank",
                "Jessi",
                "Billy",
                "Igor",
                "Molly",
                "Chelsey",
                "Alison",
                "Joe",
                "Thomas",
                "Carl",
                "Pam",
                "Jacob",
                "Keith",
                "Pearl",
                "Chemist",
                "Austin",
                "Doug",
                "Greg",
                "Wei",
                "Tobias",
                "Shirley",
                "Jack",
                "Geraldine",
                "Jerry",
                "Trent",
                "Genghis",
                "Brad",
                "CivilianNPC",
                "Harold",
                "Frank",
                "Donna",
                "Charles",
                "Beth",
                "Lisa",
                "Lily",
                "Javier",
                "Chloe",
                "George",
                "Peter",
                "Ludwig",
                "Dan",
                "Kyle",
                "Louis",
                "Player",
                "Jeremy",
                "Melissa",
                "SchizoGoblin",
                "Sam",
                "Micheal",
                "Doris",
                "Benji",
                "Lucy",
                "Jackie",
                "Kim",
                "Randy",
                "Elizabeth",
                "Billy",
                "Eugene",
                "Peggy",
                "Fiona",
                "Mick",
                "Hank",
                "Karen",
                "Joyce",
                "Ming",
                "Walter",
                "Dean",
                "Jennifer",
                "Oscar",
                "Micheal",
                "Ray",
                "Kevin",
                "Leo",
                "Jen",
                "Salvador",
                "Philip",
                "Chris",
                "Marco",
                "Dennis",
                "Dealer",
                "Meg",
                "Botanist",
                "Jane",
                "Stan",
                "Mac",
                "Andy",
                "Jeff",
                "Albert",
                "Herbert"
        };
    }
}
